Razor/Razor.WebPages/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Razor.WebPages.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Razor/Razor.WebPages/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Razor.WebPages.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Razor/Razor.WebPages/Pages/NotFound.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Razor.WebPages.Pages
{
    public class NotFoundModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Razor/Razor.WebPages/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Razor.WebPages.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Razor/Razor.WebPages/Pages/Products/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Razor.WebPages.Models;
using Razor.WebPages.Sevices;

namespace Razor.WebPages.Pages.Products
{
    public class DeleteModel : PageModel
    {
        private readonly IProductRepository _productRepository;
        [BindProperty]
        public Product product { get; set; }

        public DeleteModel(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }
        public IActionResult OnGet(int id)
        {
            product = _productRepository.GetProduct(id);

            if (product == null)
                return RedirectToPage("/NotFound");
            return Page();
        }

        public IActionResult OnPost()
        {
            Product productToDelete = _productRepository.Delete(product.id);

            if(productToDelete == null)
            {
                return RedirectToPage("/NotFound");
            }

            return RedirectToPage("Products");
        }
    }
}

Razor/Razor.WebPages/Pages/Products/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Razor.WebPages.Models;
using Razor.WebPages.Sevices;

namespace Razor.WebPages.Pages.Products
{
    public class DetailsModel : PageModel
    {
        private readonly IProductRepository _productRepository;
        public DetailsModel(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        public Product product { get; private set; }

        public IActionResult OnGet(int id)
        {
            product = _productRepository.GetProduct(id);

            if(product == null)
            {
                return RedirectToPage("/NotFound");
            }
            return Page();
        }
    }
}

Razor/Razor.WebPages/Pages/Products/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Razor.WebPages.Models;
using Razor.WebPages.Sevices;

namespace Razor.WebPages.Pages.Products
{
    public class EditModel : PageModel
    {
        private readonly IProductRepository _db;
        private readonly IWebHostEnvironment _webHostEnvirnoment;

        public EditModel(IProductRepository db, IWebHostEnvironment webHostEnvirnoment)
        {
            _db = db;
            _webHostEnvirnoment = webHostEnvirnoment;
        }
        [BindProperty]
        public Product product { get; set; }
        [BindProperty]
        public IFormFile Photo { get; set; }
        [BindProperty]
        public bool Notify { get; set; }
        public string Message { get; set; }

        public IActionResult OnGet(int? id)
        {
            if (id.HasValue)
                product = _db.GetProduct(id.Value);
            else
                product = new Product();
            if(product == null)
            {
                return RedirectToPage("/NotFound");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                if (Photo != null)
                {
                    if (product.PhotoPath != null)
                    {
                        string filePath = Path.Combine(_webHostEnvirnoment.WebRootPath, "images", product.PhotoPath);
                        System.IO.File.Delete(filePath);
                    }

                    product.PhotoPath = ProcessUploadedFile();
                }

                if (product.id > 0)
                {
                    product = _db.Update(product);

                    TempData["SeccessMessage"] = $"Update {product.name} successful";
                }
                else
                {
                    product = _db.Add(product);

                    TempData["SeccessMessage"] = $"Adding {product.name} successful";
                }
                return RedirectToPage("Products");
            }
                return Page();
        }

        public void OnPostUpdateNotificationPreferences(int id)
        {
            if (Notify == true)
                Message = "Thank you for turning on notification";
            else
                Message = "You have turned off notification";

            product = _db.GetProduct(id);
        }

        private string ProcessUploadedFile()
        {
            string uniqueFileName = null;

            if(Photo != null)
            {
                string uploadsFolders = Path.Combine(_webHostEnvirnoment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolders, uniqueFileName);

                using (var fs = new FileStream(filePath, FileMode.Create)) 
                {
                    Photo.CopyTo(fs);
                }
            }
            return uniqueFileName;
        }
    }
}

Razor/Razor.WebPages/Pages/Products/Products.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Razor.WebPages.Models;
using Razor.WebPages.Sevices;

namespace Razor.WebPages.Pages.Products
{
    public class ProductsModel : PageModel
    {
        private readonly IProductRepository _db;
        public ProductsModel(IProductRepository db)
        {
            _db = db;
        }
        public IEnumerable<Product> products { get; set; }
        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }

        public void OnGet()
        { 
            products = _db.Search(SearchTerm);
        }
    }
}

Razor/Razor.WebPages/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Razor/Razor.WebPages/Pages/NotFound.cshtml
@page
@model Razor.WebPages.Pages.NotFoundModel
@{
    ViewData["Title"] = "Not Found";
}

<div class="row">
    <div class="col text-center">
        <h1>Not Found</h1>
        <a asp-page="/Products/Products" class="btn-primary">Click here to get back to Products list page</a>
    </div>
</div>



Razor/Razor.WebPages/Pages/Products/Delete.cshtml
@page "{id}"
@model Razor.WebPages.Pages.Products.DeleteModel
@{     
    ViewData["Title"] = "Delete";
    ViewData["ShowButtons"] = false;
}

<h1 class="text-center">Delete Confirmation</h1>

<div class="alert alert-danger">
    <div class="row">
        <div class="col-12 col-md-6 col-xl-4 ofset-sm-0 ofset-md-3 ofset-xl-4">
            <partial name="_DisplayProductPartial" model="Model.product" view-data="ViewData" />
        </div>
    </div>

        <div class="row">
            <div class="col-12 col-md-6 col-xl-4 ofset-sm-0 ofset-md-3 ofset-xl-4">
                <div class="text-center text-secondary">
                    <h4>Product ID: <span class="text-primary">@Model.product.id</span></h4> <hr />
                    <h4>Product Name: <span class="text-primary">@Model.product.name</span></h4> <hr />
                    <h4>Product Price: <span class="text-primary">@Model.product.price</span></h4> <hr />
                </div>
            </div>
        </div>
        <div class="row">
            <dib class="col text-center">
                <h5>Are you sure to Delete product? - @Model.product.name</h5>

                <form method="post">
                    <button type="submit" class="btn btn-danger">Yes</button>
                    <a class="btn btn-success" asp-page="/Products/Products">No</a>
                </form>
            </dib>
        </div>
    </div>

Razor/Razor.WebPages/Pages/Products/Details.cshtml
@page
@model Razor.WebPages.Pages.Products.DetailsModel
@{      
    ViewData["Title"] = "Product Details";
    var photoPath = $"/images/{Model.product.PhotoPath}";
}

<div class="row justify-content-center m-3">
    <div class="col col-lg-8">
        <div class="card">
            <div class="card-header">
                <h1>@Model.product.name</h1>
            </div>
            <div class="card-body text-center">
                <div class="row">
                    <div class="col col-lg-9">
                        <h4 class="card-text">Product ID: @Model.product.id</h4><hr />
                        <h4 class="card-text">Product Name: @Model.product.name</h4><hr />
                        <h4 class="card-text">Product Price: @Model.product.price</h4><hr />
                    </div>
                    <div class="col col-lg-3">
                        <div style="border-right: 1px solid rbga(0,0,0,.1);">
                            <img class="card-img-top border-primary" style="background-color: #dle7ff;"src="@photoPath" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="card-footer text-center" style="background-color: rgba(0,0,0,0.25)">
                        <a asp-page="Products" class="btn-success">Back</a>
                        <a href='#' class="btn-primary">Edit</a>
                        <a href='#' class="btn-danger">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Razor/Razor.WebPages/Pages/Products/Edit.cshtml
@page   "{id:min(1)}/{handler?}"
@model Razor.WebPages.Pages.Products.EditModel
@{

    var photoPath = $"/images/{Model.product.PhotoPath}";

    var pageTitle = Model.product.id > 0 ? "Edit" : "Create";
    ViewData["Title"] = pageTitle;
}

<form method="post" asp-page-handler="UpdateNotificationPreferences">
    <div class="row text-center">
        <div class="col form-check">
            <h1>Notification preference</h1>
            <input asp-for="Notify" class="form-check-input"/>
            <label asp-for="Notify" class="form-check-label">
                Receive notification when products change
            </label><br />
            <button type="submit" class="btn btn-primary text-center">Update notification Preference</button>

            @if(!string.IsNullOrWhiteSpace(Model.Message))
            {
                <div class="alert alert-success" >
                    <p class="p-3 mt2">@Model.Message</p>
                </div>
            }
        </div>
    </div>
</form>
<hr />

<div asp-validation-summary="ModelOnly" class="text-danger text-center"></div>

<form method="post" asp-page-handler="OnPost" class="mt-3" enctype="multipart/form-data">
    <input type="hidden" asp-for="product.id" />
    <input type="hidden" asp-for="product.PhotoPath" />

    <div class="row justify-content-center m-3">
        <div class="col col-lg-8">
            <div class="card cardBoxShadow">
                <div class="card-header cardHeaderStyle text-center">
                    <div class="form-group row">
                        <label asp-for="product.name" class="col col-lg-4 col-form-label text-right">Edit Name:</label>
                        <div class="col col-lg-6">
                            <input asp-for="product.name" class="form-control" placeholder="@Model.product.name" />
                            <span asp-validation-for="product.name" class="text-danger"></span>
                        </div>
                    </div>

                </div>
                <div class="card-body cardBodyStyle text-center">
                    <div class="row">
                        <div class="col col-lg-9">
                            <h4 class="cardTextLeftFloating">Employee ID: @Model.product.id</h4><hr />

                            <div class="form-group row">
                                <label asp-for="product.price" class="col col-lg-4 col-form-label text-right">Edit Price:</label>
                                <div class="col-12 col-lg-6">
                                    <input asp-for="product.price" class="form-control mr-2" placeholder="@Model.product.price" />
                                    <span asp-validation-for="product.price" class="text-danger"></span>
                                </div>
                            </div>
                            <hr />
                        </div>

                        <div class="col col-lg-3">
                            <div>
                                <img class="card-img-top border border-primary" src="@photoPath" />
                                <div class="custom-file">
                                    <input asp-for="Photo" class="custom-file-input form-control" />
                                    <label class="custom-file-label text-left">Click here</label>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="card-footer text-center" style="background-color: rgba(0, 0, 0, 0.25);">
                                <button type="submit" class="btn btn-success">Update</button>
                                <a asp-page="index" class="btn btn-danger">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @section Scripts {
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>
        
        <partial name="_ValidationScriptsPartial" />
    }

</form>

Razor/Razor.WebPages/Pages/Products/Products.cshtml
@page
@model Razor.WebPages.Pages.Products.ProductsModel
@{
    ViewData["ShowButtons"] = true;
}

@if (TempData["SeccessMessage"] != null)
{
    <div class="alert-success text-center">
        @TempData["SeccessMessage"]
    </div>
}

<form method="get" class="mb-3">
    <div class="input-group">
        <input class="form-control" asp-for="SearchTerm" />
        <div class="input-group-append">
            <button type="submit" class="btn-primary">Search</button>
        </div>
    </div>
</form>

<h1>Products</h1>

<div class="row">
    @foreach (var item in Model.products)
    {
        <div class="col-12 col-sm-6 col-lg-4">
            <partial name="_DisplayProductPartial" model="item" view-data="ViewData" />
        </div>
    }
</div>

Razor/Razor.WebPages/Pages/Shared/_DisplayProductPartial.cshtml
@using Razor.WebPages.Models;
@model Product

@{

    var photoPath = $"/images/{Model.PhotoPath}";
    var showButtons = (bool)ViewData["ShowButtons"];
}


<div class="card-deck">
    <div class="card m-3">
        <div class="card-header text-center">
            <h3>@Model.name</h3>
        </div>
        <div class="card-body text-center">
            <img class="card-img-top imageThumnail" src="@photoPath" asp-append-version="true" />
        </div>

        @if (showButtons)
        {
            <div class="card-footer text-center">
                <a asp-page="/Products/Details" asp-route-ID="@Model.id" class="btn btn-success m-1">View</a>
                <a asp-page="/Products/Edit" asp-route-ID="@Model.id" class="btn btn-primary m-1">Edit</a>
                <a asp-page="/Products/Delete" asp-route-ID="@Model.id" class="btn btn-danger m-1">Delete</a>
            </div>
        }
    </div>
</div>

Razor/Razor.WebPages/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Razor.WebPages</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Razor.WebPages</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Products/Products">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Products/Edit">Add Product</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Razor.WebPages - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>